apiVersion: apps.open-cluster-management.io/v1
kind: PlacementRule
metadata:
  name: 5gplacements-nad-istanbulclusterupf
  namespace: default
spec:
  clusterConditions:
  - status: "True"
    type: ManagedClusterConditionAvailable
  clusterSelector:
    matchExpressions:
      - {key: clusterid, operator: In, values: ["istanbulclusterupf"]}
