apiVersion: apps.open-cluster-management.io/v1
kind: PlacementRule
metadata:
  name: 5gplacements-nad
  namespace: default
spec:
  clusterConditions:
  - status: "True"
    type: ManagedClusterConditionAvailable
  clusterSelector:
    matchExpressions:
      - {key: cluster, operator: In, values: ["testdonotuse"]}
