resources:
- open5gs-namespace-policy.yaml
- open5gsupf-namespace-policy.yaml
- 5gplacements.yaml
- 5gplacements-open5gs.yaml
- 5gplacements-open5gsupf.yaml
- 5gplacements-placementule.yaml
- enablesctp.yaml
