apiVersion: app.k8s.io/v1beta1
kind: Application
metadata:
  name: open5gspolicies
  namespace: default
spec:
  selector:
    matchExpressions:
    - key: name  
      operator: In
      values:
      - open5gs 
  componentKinds:
  - group: apps.open-cluster-management.io/v1
    kind: Subscription

