apiVersion: policy.open-cluster-management.io/v1
kind: Policy
metadata:
  name: open5gs-nad-abudhabiclusterupf
  namespace: open5gsupf
  annotations:
    policy.open-cluster-management.io/standards: 5G Openshift Standarts
    policy.open-cluster-management.io/categories: 5G Configuration Management
    policy.open-cluster-management.io/controls: 5G Baseline Configuration
spec:
  remediationAction: enforce
  disabled: false
  policy-templates:
  - objectDefinition:
      apiVersion: policy.open-cluster-management.io/v1
      kind: ConfigurationPolicy
      metadata:
        name: open5gs-nad-abudhabiclusterupf
      spec:
        remediationAction: enforce # will be overridden by remediationAction in parent policy
        severity: low
        namespaceSelector:
          exclude: ["kube-*"]
          include: ["default"]
        object-templates:
          - complianceType: musthave
            objectDefinition:
              kind: NetworkAttachmentDefinition
              apiVersion: k8s.cni.cncf.io/v1
              metadata:
                name: testuserplane
                namespace: open5gsupf
              spec:
                config: '{ "cniVersion": "0.3.1", "name": "testuplane", "type": "ipvlan", "master": "ens8", "mode": "l2", "ipam": {"type": "static","addresses": [{"address": "192.168.50.201/24"}] } }'
